apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-webapp
  labels:
    app: react-webapp
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: react-webapp
  template:
    metadata:
      labels:
        app: react-webapp
    spec:
      containers:
      - name: react-webapp
        image: 
        ports:
        - containerPort: 3000
