# Deploy ClusterIP Services
apiVersion: v1
kind: Service
metadata:
  name: react-webapp-service
  labels:
    app: react-webapp

spec:
  selector:
    app: react-webapp

  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000

